package controllers.console;

public enum Constants {
    EXIT , ACCOUNT_EXISTS , ACCOUNT_CREATE_SUCCESSFULLY, INVALID_USERNAME , SUCCESSFUL_LOGIN  , WRONG_PASSWORD, NO_ACCOUNT_LOGGED_IN, NOT_ENOUGH_MONEY, HAD_BOUGHT_BEFORE, SUCCESSFUL_BUY
}