package controllers;

public enum Constants {
    EXIT ,
    ACCOUNT_EXISTS , ACCOUNT_CREATE_SUCCESSFULLY, INVALID_USERNAME , SUCCESSFUL_LOGIN  , WRONG_PASSWORD, NO_ACCOUNT_LOGGED_IN, NOT_EXISTS,
    NOT_ENOUGH_MONEY, HAD_BOUGHT_BEFORE, SUCCESSFUL_BUY, NO_HERO, NOT_20_CARDS, CORRECT_DECK, MULTIPLE_HEROS
}